### ISSUE TITLE
Extract this file with QuickBMS first error, already unpacked.

### ISSUE THREAD

**Issue by srabouin** [umop-aplsdn/sc_decode#1]
Nice job figuring out the structure! Haven't had luck using your script yet though, maybe this is something you have gone through already?

I'm trying to use the ui.sc from 1.6.0 which has been unpacked with the quickbms script, but it's telling me 

> Extract this file with QuickBMS first; then, try to pass it to this script

Did I miss a step somewhere?

**Comment by knobse** [comment]
you need to remove the file-extension of the file , or remove the file-extenstion check in the script

**Comment by srabouin** [comment]
That was easy, thanks, seems to work --I will give this a shot and see if I can help :)
