### ISSUE TITLE
QuickBMS SC File Extraction

### ISSUE THREAD

**Issue by moien007** [umop-aplsdn/sc_decode#4]
Hi sir,

how can i extract sc files with QuickBMS ? Any script ?

**Comment by knobse** [comment]
http://aluigi.altervista.org/bms/clash_royale.bms

**Comment by umop-aplsdn** [comment]
Just posted a 'getting started' guide on the wiki: https://github.com/umop-aplsdn/sc_decode/wiki/Getting-started
